// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package roo.nw.model;

import javax.persistence.EntityListeners;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;
import roo.nw.model.Category;

privileged aspect Category_Roo_Jpa_Audit {
    
    declare @type: Category: @EntityListeners(AuditingEntityListener.class);
    
}
