// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package roo.nw.model.dod;

import roo.nw.model.City;
import roo.nw.model.Country;
import roo.nw.model.Customer;
import roo.nw.model.Region;
import roo.nw.model.dod.CustomerFactory;

privileged aspect CustomerFactory_Roo_JpaEntityFactory {
    
    /**
     * Creates a new {@link Customer} with the given index.
     * 
     * @param index position of the Customer
     * @return a new transient Customer
     */
    public Customer CustomerFactory.create(int index) {
        Customer obj = new Customer();
        setAddress(obj, index);
        setCity(obj, index);
        setCompanyName(obj, index);
        setContactName(obj, index);
        setContactTitle(obj, index);
        setCountry(obj, index);
        setEmail(obj, index);
        setFax(obj, index);
        setPhone(obj, index);
        setPostalCode(obj, index);
        setRegion(obj, index);
        return obj;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param obj
     * @param index
     */
    public void CustomerFactory.setAddress(Customer obj, int index) {
        String address = "address_" + index;
        obj.setAddress(address);
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param obj
     * @param index
     */
    public void CustomerFactory.setCity(Customer obj, int index) {
        City city = null;
        obj.setCity(city);
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param obj
     * @param index
     */
    public void CustomerFactory.setCompanyName(Customer obj, int index) {
        String companyName = "companyName_" + index;
        obj.setCompanyName(companyName);
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param obj
     * @param index
     */
    public void CustomerFactory.setContactName(Customer obj, int index) {
        String contactName = "contactName_" + index;
        obj.setContactName(contactName);
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param obj
     * @param index
     */
    public void CustomerFactory.setContactTitle(Customer obj, int index) {
        String contactTitle = "contactTitle_" + index;
        obj.setContactTitle(contactTitle);
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param obj
     * @param index
     */
    public void CustomerFactory.setCountry(Customer obj, int index) {
        Country country = null;
        obj.setCountry(country);
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param obj
     * @param index
     */
    public void CustomerFactory.setEmail(Customer obj, int index) {
        String email = "foo" + index + "@bar.com";
        obj.setEmail(email);
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param obj
     * @param index
     */
    public void CustomerFactory.setFax(Customer obj, int index) {
        String fax = "fax_" + index;
        obj.setFax(fax);
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param obj
     * @param index
     */
    public void CustomerFactory.setPhone(Customer obj, int index) {
        String phone = "phone_" + index;
        obj.setPhone(phone);
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param obj
     * @param index
     */
    public void CustomerFactory.setPostalCode(Customer obj, int index) {
        String postalCode = "postalCode_" + index;
        obj.setPostalCode(postalCode);
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param obj
     * @param index
     */
    public void CustomerFactory.setRegion(Customer obj, int index) {
        Region region = null;
        obj.setRegion(region);
    }
    
}
