// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package roo.nw.model.dod;

import org.springframework.beans.factory.annotation.Configurable;
import roo.nw.model.dod.PurchaseOrderDataOnDemand;

privileged aspect PurchaseOrderDataOnDemand_Roo_Configurable {
    
    declare @type: PurchaseOrderDataOnDemand: @Configurable;
    
}
