// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package roo.nw.model.dod;

import roo.nw.model.City;
import roo.nw.model.Country;
import roo.nw.model.Region;
import roo.nw.model.Store;
import roo.nw.model.dod.StoreFactory;

privileged aspect StoreFactory_Roo_JpaEntityFactory {
    
    /**
     * Creates a new {@link Store} with the given index.
     * 
     * @param index position of the Store
     * @return a new transient Store
     */
    public Store StoreFactory.create(int index) {
        Store obj = new Store();
        setAddress(obj, index);
        setCity(obj, index);
        setCountry(obj, index);
        setName(obj, index);
        setPhone(obj, index);
        setPostalCode(obj, index);
        setRegion(obj, index);
        return obj;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param obj
     * @param index
     */
    public void StoreFactory.setAddress(Store obj, int index) {
        String address = "address_" + index;
        obj.setAddress(address);
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param obj
     * @param index
     */
    public void StoreFactory.setCity(Store obj, int index) {
        City city = null;
        obj.setCity(city);
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param obj
     * @param index
     */
    public void StoreFactory.setCountry(Store obj, int index) {
        Country country = null;
        obj.setCountry(country);
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param obj
     * @param index
     */
    public void StoreFactory.setName(Store obj, int index) {
        String name = "name_" + index;
        obj.setName(name);
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param obj
     * @param index
     */
    public void StoreFactory.setPhone(Store obj, int index) {
        String phone = "phone_" + index;
        obj.setPhone(phone);
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param obj
     * @param index
     */
    public void StoreFactory.setPostalCode(Store obj, int index) {
        String postalCode = "postalCode_" + index;
        obj.setPostalCode(postalCode);
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param obj
     * @param index
     */
    public void StoreFactory.setRegion(Store obj, int index) {
        Region region = null;
        obj.setRegion(region);
    }
    
}
