// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package roo.nw.model.dod;

import roo.nw.model.City;
import roo.nw.model.Country;
import roo.nw.model.Region;
import roo.nw.model.Supplier;
import roo.nw.model.dod.SupplierFactory;

privileged aspect SupplierFactory_Roo_JpaEntityFactory {
    
    /**
     * Creates a new {@link Supplier} with the given index.
     * 
     * @param index position of the Supplier
     * @return a new transient Supplier
     */
    public Supplier SupplierFactory.create(int index) {
        Supplier obj = new Supplier();
        setAddress(obj, index);
        setCity(obj, index);
        setCompanyName(obj, index);
        setContactName(obj, index);
        setContactTitle(obj, index);
        setCountry(obj, index);
        setFax(obj, index);
        setPhone(obj, index);
        setPostalCode(obj, index);
        setRegion(obj, index);
        setWeb(obj, index);
        return obj;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param obj
     * @param index
     */
    public void SupplierFactory.setAddress(Supplier obj, int index) {
        String address = "address_" + index;
        obj.setAddress(address);
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param obj
     * @param index
     */
    public void SupplierFactory.setCity(Supplier obj, int index) {
        City city = null;
        obj.setCity(city);
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param obj
     * @param index
     */
    public void SupplierFactory.setCompanyName(Supplier obj, int index) {
        String companyName = "companyName_" + index;
        obj.setCompanyName(companyName);
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param obj
     * @param index
     */
    public void SupplierFactory.setContactName(Supplier obj, int index) {
        String contactName = "contactName_" + index;
        obj.setContactName(contactName);
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param obj
     * @param index
     */
    public void SupplierFactory.setContactTitle(Supplier obj, int index) {
        String contactTitle = "contactTitle_" + index;
        obj.setContactTitle(contactTitle);
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param obj
     * @param index
     */
    public void SupplierFactory.setCountry(Supplier obj, int index) {
        Country country = null;
        obj.setCountry(country);
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param obj
     * @param index
     */
    public void SupplierFactory.setFax(Supplier obj, int index) {
        String fax = "fax_" + index;
        obj.setFax(fax);
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param obj
     * @param index
     */
    public void SupplierFactory.setPhone(Supplier obj, int index) {
        String phone = "phone_" + index;
        obj.setPhone(phone);
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param obj
     * @param index
     */
    public void SupplierFactory.setPostalCode(Supplier obj, int index) {
        String postalCode = "postalCode_" + index;
        obj.setPostalCode(postalCode);
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param obj
     * @param index
     */
    public void SupplierFactory.setRegion(Supplier obj, int index) {
        Region region = null;
        obj.setRegion(region);
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param obj
     * @param index
     */
    public void SupplierFactory.setWeb(Supplier obj, int index) {
        String web = "web_" + index;
        obj.setWeb(web);
    }
    
}
