// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package roo.nw.repository;

import static org.assertj.core.api.Assertions.assertThat;

import io.springlets.data.domain.GlobalSearch;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Before;
import org.junit.Rule;
import org.junit.Test;
import org.junit.rules.ExpectedException;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest;
import org.springframework.context.annotation.Import;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageRequest;
import org.springframework.test.context.junit4.SpringRunner;
import roo.nw.application.config.SpringDataJpaDetachableRepositoryConfiguration;
import roo.nw.model.Product;
import roo.nw.model.dod.DataOnDemandConfiguration;
import roo.nw.model.dod.ProductDataOnDemand;
import roo.nw.repository.ProductRepository;
import roo.nw.repository.ProductRepositoryIT;

privileged aspect ProductRepositoryIT_Roo_RepositoryJpaIntegrationTest {
    
    declare @type: ProductRepositoryIT: @RunWith(SpringRunner.class);
    
    declare @type: ProductRepositoryIT: @DataJpaTest;
    
    declare @type: ProductRepositoryIT: @Import({ DataOnDemandConfiguration.class, SpringDataJpaDetachableRepositoryConfiguration.class });
    
    /**
     * TODO Auto-generated attribute documentation
     * 
     */
    @Rule
    public ExpectedException ProductRepositoryIT.thrown = ExpectedException.none();
    
    /**
     * TODO Auto-generated attribute documentation
     * 
     */
    @Autowired
    private ProductRepository ProductRepositoryIT.repository;
    
    /**
     * TODO Auto-generated attribute documentation
     * 
     */
    @Autowired
    private ProductDataOnDemand ProductRepositoryIT.dod;
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @return ProductRepository
     */
    public ProductRepository ProductRepositoryIT.getRepository() {
        return repository;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @return ProductDataOnDemand
     */
    public ProductDataOnDemand ProductRepositoryIT.getDod() {
        return dod;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     */
    @Before
    public void ProductRepositoryIT.checkDataOnDemandHasInitializedCorrectly() {
        assertThat(getDod().getRandomProduct())
            .as("Check data on demand for 'Product' initializes correctly by getting a random Product")
            .isNotNull();
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     */
    @Test
    public void ProductRepositoryIT.countShouldReturnExpectedValue() {
        // Verify
        assertThat(getRepository().count()).as("Check there are available 'Product' entries").isGreaterThan(0);
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     */
    @Test
    public void ProductRepositoryIT.findOneShouldReturnExistingProduct() {
        // Setup
        Long id = getRandomProductId();
        
        // Exercise
        Product product = getRepository().findOne(id);
        
        // Verify
        assertThat(product).as("Check that findOne illegally returned null for id %s", id).isNotNull();
        assertThat(id).as("Check the identifier of the found 'Product' is the same used to look for it")
            .isEqualTo(product.getId());
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     */
    @Test
    public void ProductRepositoryIT.findAllShouldReturnAllProducts() {
        // Setup
        assertThat(getRepository().count())
            .as("Check the number of entries is not too big (250 entries). "
                + "If it is, please review the tests so it doesn't take too long to run them")
            .isLessThan(250);
        
        // Exercise
        List<Product> result = getRepository().findAll();
        
        // Verify
        assertThat(result).as("Check 'findAll' returns a not null list of entries").isNotNull();
        assertThat(result.size()).as("Check 'findAll' returns a not empty list of entries")
            .isGreaterThan(0);
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     */
    @Test
    public void ProductRepositoryIT.persistShouldGenerateIdValue() {
        // Setup
        // Exercise
        Product product = getDod().getNewRandomTransientProduct();
        
        // Verify
        assertThat(product).as("Check the Data on demand generated a new non null 'Product'").isNotNull();
        assertThat(product.getId()).as("Check the Data on demand generated a new 'Product' whose id is null")
            .isNull();
        try {
            product = getRepository().saveAndFlush(product);
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter
                .hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".")
                    .append(cv.getPropertyPath()).append(": ").append(cv.getMessage())
                    .append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        assertThat(product.getId()).as("Check a 'Product' (%s) id is not null after been persisted", product)
            .isNotNull();
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     */
    @Test
    public void ProductRepositoryIT.deleteShouldMakeProductUnavailable() {
        // Setup
        Long id = getRandomProductId();
        Product product = getRepository().findOne(id);
        
        // Exercise
        getRepository().delete(product);
        
        // Verify
        assertThat(getRepository().findOne(id))
        .as("Check the deleted 'Product' %s is no longer available with 'findOne'", product).isNull();
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     */
    @Test
    public void ProductRepositoryIT.findAllCustomNotFilteredNotPagedShouldReturnAllProducts() {
        // Exercise
        Page<Product> all = getRepository().findAll((GlobalSearch) null, new PageRequest(0, getDod().getSize()));
        
        // Verify
        assertThat(all.getNumberOfElements())
            .as("Check 'findAll' with null 'GlobalSearch' and no pagination returns all entries")
            .isEqualTo(getDod().getSize());
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     */
    @Test
    public void ProductRepositoryIT.findAllCustomNotFilteredPagedShouldReturnAProductsPage() {
        // Exercise
        Page<Product> all = getRepository().findAll((GlobalSearch) null, new PageRequest(0, 3));
        
        // Verify
        assertThat(all.getNumberOfElements())
            .as("Check result number is not greater than the page size").isLessThanOrEqualTo(3);
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @return Long
     */
    private Long ProductRepositoryIT.getRandomProductId() {
        Product product = getDod().getRandomProduct();
        Long id = product.getId();
        assertThat(id).as("Check the Data on demand generated a 'Product' with an identifier").isNotNull();
        return id;
    }
    
}
